import Layout from '@/components/layout/Layout'
import '../styles/globals.css'
import OpenMenuContextProvider from '@/context/OpenMenuContextProvider'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="ar" dir='rtl'>
      <head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>

      <body >
        <OpenMenuContextProvider>
          <Layout>

            {children}
          </Layout>
        </OpenMenuContextProvider>
      </body>
    </html>
  )
}
